### ISSUE TITLE
Migrate to the new data model

### ISSUE THREAD

**Issue by LVOL98** [NorseKode/Waultar-App#173]

**Comment by gustavjohansen98** [comment]
- [x] full text search
- [ ] text search by category 
- [x] connect with UI base model (more or less done, but will need your help and opinion)
- [x] image relations (uri and meta data is put correctly, and the images are ready to be used in classification)
- [ ] video relations
- [ ] file relations
- [ ] link relations 
- [ ] timeseries buckets (help  needed for processing timestamps in parser pipeline)
